# This is a basic workflow to help you get started with Actions

name: Create VMs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Gcloud vm instance create
        env: 
          project_name: ${{ secrets.GCLOUD_PROJECT_NAME }}
          token_file: ${{ secrets.GCLOUD_TOKEN }}
        run: |
          chmod +x pn_assignment10/run.sh
          gcloud config set account pardhasaradhisastry.nemani@valpo.edu
          pn_assignment10/run.sh project_name token_file
